const data = [
  {
    id: 1,
    admission_number: 1000,
    first_name: 'Aishwarya',
    last_name: "Joy",
    class_division: {
      id:1,
      name:"1A",
    },
    contact_number:8943795775,
    email:"aishwarya@gmail.com",
    fee_status:"NP",
    is_active:true,
  },
    {
      id: 2,
      admission_number: 1001,
      first_name: 'Aparna',
      last_name: "Joy",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:8943795775,
      email:"aishwarya@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 3,
      admission_number: 1003,
      first_name: 'Jake',
      last_name: "James",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999999,
      email:"jake123@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 4,
      admission_number: 1004,
      first_name: 'Arun',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999999,
      email:"jake123@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 5,
      admission_number: 1005,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999999,
      email:"jake123@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 6,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 7,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 8,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 9,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 10,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 11,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 12,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 13,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 14,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 15,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 16,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 17,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 18,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 19,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 20,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 21,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },
    {
      id: 22,
      admission_number: 1006,
      first_name: 'Malavika',
      last_name: "Thomas",
      class_division: {
        id:1,
        name:"1A",
      },
      contact_number:9999999345,
      email:"mal@gmail.com",
      fee_status:"NP",
      is_active:true,
    },

  ];
  export default data;